version: '3'

services:
  ws-bridge:
    image: ctonic/ws-bridge
    build: https://github.com/ctonic/Docker-ROS-ws-bridge.git
  nvidia-vnc:
    image: ctonic/nvidia-vnc
    build: https://github.com/ctonic/Docker-nvidia-vnc-xvfb.git
  agent:
    

