#!/bin/bash

# SSH Stuff: register public key and start ssh server
mkdir ~/.ssh
cp /ssh/id_rsa.pub ~/.ssh/authorized_keys
/usr/sbin/sshd& # run SSH server

source /opt/ros/kinetic/setup.bash
echo Starting roscore
roscore& sleep 5
echo Starting rosbridge_server and rosbridge_websocket
roslaunch rosbridge_server rosbridge_websocket.launch

echo "Running the given parameters: $@"
exec "$@"
