#!/bin/bash

# make sure SSH server is running
/usr/sbin/sshd

source /opt/ros/kinetic/setup.bash
echo Starting roscore
roscore& sleep 5
echo Starting rosbridge_server and rosbridge_websocket
roslaunch rosbridge_server rosbridge_websocket.launch
