#!/bin/bash

# echo "Starting port forwarding of port 9090 from root@c_ros_bridge"
# socat TCP4-LISTEN:9090,fork,reuseaddr TCP4:c_ros_bridge:9090 &

# export DISPLAY=${DISPLAY:-:0} # Select screen 0 by default.

echo Running xdpyinfo
xdpyinfo
echo Starting x11vnc on display $DISPLAY
x11vnc -bg -forever -nopw -quiet -shared -display WAIT$DISPLAY &
echo "IP: $(hostname -I) ($(hostname))"

# x11vnc run with the following params: (Source: http://www.karlrunge.com/x11vnc/x11vnc_opts.html)
# - forever: keep listening after someone disconnects
# - bg
# -nopw
# -quiet
# -shared: Allow several vnc connections at the same time

echo "Running the given parameters: $@"
exec "$@"
