#!/bin/bash

echo "Running start_vnc script"

echo "Installing SSH keys"
mkdir ~/.ssh
cp /ssh/id_rsa /ssh/id_rsa.pub ~/.ssh
chmod a-rw ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
chmod u+rw ~/.ssh/id_rsa ~/.ssh/id_rsa.pub

echo "Starting port forwarding of port 9090 from root@c_ws_bridge"
# ssh -o StrictHostKeyChecking=no -4 -N -T -L 9090:localhost:9090 root@c_ws_bridge&   # VERY SLOW
socat TCP4-LISTEN:9090,fork,reuseaddr TCP4:c_ws_bridge:9090

echo "Starting VNC"
export DISPLAY=${DISPLAY:-:0} # Select screen 0 by default.

xdpyinfo
if which x11vnc &>/dev/null; then
  ! pgrep -a x11vnc && x11vnc -bg -forever -nopw -quiet -shared -display WAIT$DISPLAY &
fi
! pgrep -a Xvfb && Xvfb $DISPLAY -screen 0 1024x768x16 &
sleep 1
if which fluxbox &>/dev/null; then
  ! pgrep -a fluxbox && fluxbox 2>/dev/null &
fi
echo "IP: $(hostname -I) ($(hostname))"

# x11vnc run with the following params: (Source: http://www.karlrunge.com/x11vnc/x11vnc_opts.html)
# - forever: keep listening after someone disconnects
# - bg
# -nopw
# -quiet
# -shared: Allow several vnc connections at the same time

echo "Running the given parameters: $@"
exec "$@"
