#!/bin/bash
#set -x

export DISPLAY=:0

echo "Starting Xorg"
Xorg -noreset +extension RANDR +extension RENDER -logfile ./xdummy.log -config ./xorg.conf "$DISPLAY" &
# +extension GLX 

sleep 3

echo "Starting x11vnc"
x11vnc -bg -forever -nopw -quiet -shared -display WAIT$DISPLAY &

echo "Running the given parameters: $@"
exec "$@"
# if [ -z "$@" ]; then
# fi
